version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - |
        npx hardhat node &
        npx hardhat compile
        npx hardhat run scripts/sample-script.js --network localhost >> .env.local
      - npm run build
      - mv .env.local dist/ 
artifacts:
  files:
    - 'dist/*'
  base-directory: 'src/artifacts'