version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - |
        npx hardhat node &
        npx hardhat compile
        npx hardhat run scripts/sample-script.js --network localhost >> .env.local
      - npm run build
      - mv .env.local dist/
      - ls -la
      - cd dist
      - ls -la
artifacts:
  files:
    - ./dist/**
  base-directory: 'src/artifacts'