version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npx hardhat compile
      - npx hardhat run scripts/fire_guys.js --network sepolia >> .env.local
      - npx hardhat run scripts/lh_memories.js --network sepolia >> .env.local
      - npm run build
      - cat .env.local
      - mv .env.local dist/
      - cp -r src/artifacts dist/
      - ls -la
      - cd dist
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
